import { texts } from '~/texts'

let textData = texts.simulation
if (typeof LM_PAGE !== 'undefined')
  textData = LM_PAGE.database?.value?.texts?.['module-simulation']

const STATICS = {
  VALIDE: textData.valide,
  PLUS_34_ANS: textData.plus34ans,
  MOIS_ACTIVITE_12: textData.moisActivite12,
  MOIS_ACTIVITE_24: textData.moisActivite24,
  SITUATION_PERSO_MARIEE: textData.situationPersoMariee,
  CONJOINT_MOINS_60_ANS: textData.conjointMoins60ans,
  REVENUS_1484: textData.revenus1484,
  REVENUS_942: textData.revenus942,
  REVENUS_577: textData.revenus577,
  ENFANT_MOINS_18_ANS: textData.enfantMoins18ans,
  INSCRITE_PLUS_4_ANS: textData.inscritePlus4ans,
  PAS_CHANGEMENT_ADRESSE: textData.pasChangementAdresse,
  PAS_CHANGEMENT_LOYER: textData.pasChangementLoyer,
  MAIL_4_MOIS: textData.mail4mois,
  ENTRE_35_ET_60_ANS: textData.entre35et60ans,
  ENFANT_MOINS_12_ANS: textData.enfantMoins12ans,
  VALIDES: textData.valides,
  REVENUS_STABLES: textData.revenusStables,
  ACTIVITE_SALARIEE: textData.activiteSalariee,
  PAS_MINIMA_SOCIAUX: textData.pasMinimaSociaux,
  SITUATION_PERSO_MARIE: textData.situationPersoMarie,
  INSCRIT_PLUS_4_ANS: textData.inscritPlus4ans,
  TOUCHE_AAH: textData.toucheAAH,
  SITUATION_PERSO_DIVORCEE: textData.situationPersoDivorcee,
  JAMAIS_CONTROLE: textData.jamaisControle,
}

// présentation de l'algo
const part1 = [
  // voilà Nathalie, 51 ans, salariée
  {
    id: 0,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_12,
      situation_perso: '',
      conjoint: '',
      revenus: '',
      enfant: '',
      inscription_caf: '',
      adresse: '',
      loyer: '',
      mail: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      OPT_MACT12: '02:0.5-14.5',
      NBM_ODMS_quant: '0 < x <1',
      TYPAAH: '0',
      TUT_P: '0',
      STATUETU: '0',
    },
  },
  // elle est mariée avec Philippe 57 ans
  {
    id: 1,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: '',
      enfant: '',
      inscription_caf: '',
      adresse: '',
      loyer: '',
      mail: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      OPT_MACT12: '03:14.5-HIGH',
      NBM_ODMS_quant: '0 < x <1',
      TYPAAH: '0',
      TUT_P: '0',
      STATUETU: '0',
    },
  },
  // ils gagnent chacun 1500 euros par mois
  {
    id: 2,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_1484,
      enfant: '',
      inscription_caf: '',
      adresse: '',
      loyer: '',
      mail: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      OPT_MACT12: '03:14.5-HIGH',
      NBM_ODMS_quant: '0 < x <1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '1483.33 < x <=19745',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  // elle a 2 enfants : un de 16 ans, un de 18 ans
  {
    id: 3,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: '',
      loyer: '',
      mail: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      NBM_ODMS_quant: '0 < x <1',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  // elle n'a pas déménagé depuis 18 mois
  {
    id: 4,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  // elle a envoyé un mail à sa CAF il y a 6 mois
  {
    id: 5,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  {
    id: 6,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  {
    id: 7,
    part: 1,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
]

// effets de seuil
// animer l'âge au scroll -> passage de cat 1 à cat 2
const part2 = [
  // conjoint de moins de 60 ans
  {
    id: 0,
    part: 2,
    baseAge: 57,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: '',
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  // conjoint de plus de 60 ans
  {
    id: 1,
    part: 2,
    baseAge: 57,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: '',
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  // conjoint de plus de 60 ans
  {
    id: 2,
    part: 2,
    baseAge: 60,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: '',
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: '60 ET PLUS',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
]

// hauts revenus
// représenter plage min-max
const part3 = [
  {
    id: 0,
    part: 4,
    name: 'couple',
    params: {
      age: STATICS.ENTRE_35_ET_60_ANS,
      enfants: STATICS.ENFANT_MOINS_12_ANS,
      valides: STATICS.VALIDES,
      revenus: STATICS.REVENUS_STABLES,
      situation_pro: STATICS.ACTIVITE_SALARIEE,
      minima: STATICS.PAS_MINIMA_SOCIAUX,
      jamaisControle: STATICS.JAMAIS_CONTROLE,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      NADRESS18_quant: '0 < x <1',
      COMPANTRIM: 'STABLE',
      SEQFAM: '23XXX',
      OPT_MACT12: '03:14.5-HIGH',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      OPT_NBPIE_DSIT18: '01:LOW -0.5, MISSIN',
      FGRESTRI18_quant: '0 < x <1',
      TYPAAH: '0',
      TOPEN19: '0',
      TOPENF1218_P: '0',
      TUT_P: '0',
      RUC_RED_quant: '1483.33 < x <=19745',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
      MOICONTVER_quant: 'MISSAUT',
    },
  },
]

// discriminations aah
const part4 = [
  {
    id: 0,
    part: 3,
    name: 'Michel',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_12,
      situation_perso: STATICS.SITUATION_PERSO_MARIE,
      revenus: STATICS.REVENUS_942,
      enfantMoins18ans: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRIT_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
      aah: '',
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  {
    id: 1,
    part: 3,
    name: 'Abel',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_12,
      situation_perso: STATICS.SITUATION_PERSO_MARIE,
      revenus: STATICS.REVENUS_942,
      enfantMoins18ans: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRIT_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
      aah: STATICS.TOUCHE_AAH,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      FGRESTRI18_quant: '1 < x <7',
      NBM_ODMS_quant: '32 < x < 500',
      TYPAAH: '1',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
]

const part5 = [
  {
    id: 0,
    part: 5,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_24,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_942,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '23XXX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '03:14.5-HIGH',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '942 < x <1483.33',
      STATUETU: '0',
      TXEFF_P: '0ALETTXEFF 0A35',
    },
  },
  {
    id: 1,
    part: 5,
    name: 'Nathalie',
    params: {
      valide: STATICS.VALIDE,
      age: STATICS.PLUS_34_ANS,
      situation_pro: STATICS.MOIS_ACTIVITE_12,
      situation_perso: STATICS.SITUATION_PERSO_DIVORCEE,
      conjoint: STATICS.CONJOINT_MOINS_60_ANS,
      revenus: STATICS.REVENUS_577,
      enfant: STATICS.ENFANT_MOINS_18_ANS,
      inscription_caf: STATICS.INSCRITE_PLUS_4_ANS,
      adresse: STATICS.PAS_CHANGEMENT_ADRESSE,
      loyer: STATICS.PAS_CHANGEMENT_LOYER,
      mail: STATICS.MAIL_4_MOIS,
    },
    scoreData: {
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      AGECON_quant: 'MISSAUT',
      AGERESP_quant: 'MISSAUT',
      COMPANTRIM: 'STABLE',
      FGRESTRI18_quant: '0 < x <1',
      SEQFAM: '456XX',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MACT12: '02:0.5-14.5',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      NADRESS18_quant: '0 < x <1',
      NBM_ODMS_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TOPENF1218_P: '1',
      TYPAAH: '0',
      TUT_P: '0',
      RUC_RED_quant: '577 < x <942',
      STATUETU: '0',
      TXEFF_P: '35ETPLUS',
    },
  },
]

// const config = [...part1, ...part2, ...part3, ...part4, ...part5]
const config = [...part3]

export { part1, part2, part3, part4, part5, config }
