import { texts } from '~/texts'

let textData = {}
if (typeof LM_PAGE !== 'undefined')
  textData = LM_PAGE.database?.value?.texts?.['module-simulation']

const STATICS = {
  FEMME: textData.femme,
  AGE: textData.age,
  SITUATION_PRO_SALARIEE: textData.situationProSalariee,
  SITUATION_PERSO_MARIEE: textData.situationPersoMariee,
  SITUATION_PERSO_DIVORCEE: textData.situationPersoDivorcee,
  CONJOINT_AGE: textData.conjointAge,
  REVENUS_1484: textData.revenus1484,
  REVENUS_942: textData.revenus942,
  REVENUS_577: textData.revenus577,
  ENFANTS_MOINS_18_ANS: textData.enfantsMoins18ans,
  PAS_DEMENAGE_18_MOIS: textData.pasDemenage18mois,
  MAIL_6_MOIS: textData.mail6mois,
  TOUCHE_AAH: textData.toucheAAH,
}

// présentation de l'algo
const part1 = [
  // voilà Nathalie, 51 ans, salariée
  {
    id: 0,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: '',
      conjoint_age: '',
      revenus: '',
      enfants: '',
      demenagements: '',
      mail: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      TITUBANC: '2',
      OPT_MACT12: '02:0.5-14.5',
    },
  },
  // elle est mariée avec Philippe 57 ans
  {
    id: 1,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint_age: STATICS.CONJOINT_AGE,
      revenus: '',
      enfants: '',
      demenagements: '',
      mail: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      AGECON_quant: 'MISSAUT',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
    },
  },
  // ils gagnent chacun 1500 euros par mois
  {
    id: 2,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint_age: STATICS.CONJOINT_AGE,
      revenus: STATICS.REVENUS_1484,
      enfants: '',
      demenagements: '',
      mail: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      AGECON_quant: 'MISSAUT',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      RUC_RED_quant: '1483.33 < x <=19745',
    },
  },
  // elle a 2 enfants : un de 16 ans, un de 18 ans
  {
    id: 3,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint_age: STATICS.CONJOINT_AGE,
      revenus: STATICS.REVENUS_942,
      enfants: STATICS.ENFANTS_MOINS_18_ANS,
      demenagements: '',
      mail: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      RUC_RED_quant: '942 < x <1483.33',
    },
  },
  // elle n'a pas déménagé depuis 18 mois
  {
    id: 4,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint_age: STATICS.CONJOINT_AGE,
      revenus: STATICS.REVENUS_942,
      enfants: STATICS.ENFANTS_MOINS_18_ANS,
      demenagements: STATICS.PAS_DEMENAGE_18_MOIS,
      mail: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
    },
  },
  // elle a envoyé un mail à sa CAF il y a 6 mois
  {
    id: 5,
    part: 1,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      conjoint_age: STATICS.CONJOINT_AGE,
      revenus: STATICS.REVENUS_942,
      enfants: STATICS.ENFANTS_MOINS_18_ANS,
      demenagements: STATICS.PAS_DEMENAGE_18_MOIS,
      mail: STATICS.MAIL_6_MOIS,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
    },
  },
]

// effets de seuil
// animer l'âge au scroll -> passage de cat 1 à cat 2
const part2 = [
  // conjoint de moins de 60 ans
  {
    id: 0,
    part: 2,
    baseAge: 57,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
    },
  },
  // conjoint de plus de 60 ans
  {
    id: 1,
    part: 2,
    baseAge: 60,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      AGECON_quant: '60 ET PLUS',
    },
  },
  {
    id: 2,
    part: 2,
    baseAge: 63,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      AGECON_quant: '60 ET PLUS',
    },
  },
]

// discriminations
const part3 = [
  // reprenons Nathalie
  {
    id: 0,
    part: 3,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      revenus: STATICS.REVENUS_942,
      aah: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
    },
  },
  // handicap
  {
    id: 1,
    part: 3,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      revenus: STATICS.REVENUS_942,
      aah: STATICS.TOUCHE_AAH,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      FGRESTRI18_quant: '1 < x <7',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      TYPAAH: '1',
      NBM_ODMS_quant: '32 < x < 500',
      FGRESTRI18_quant: '1 < x <7',
    },
  },
  // situation initiale
  {
    id: 2,
    part: 3,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_MARIEE,
      revenus: STATICS.REVENUS_942,
      aah: '',
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
    },
  },
  // monoparentalité + baisse de revenus
  {
    id: 3,
    part: 3,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_DIVORCEE,
      revenus: STATICS.REVENUS_577,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '456XX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '02:0.5-14.5',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      COMPANTRIM: 'BAISSE',
      RUC_RED_quant: '577 < x <942',
      TXEFF_P: '35ETPLUS',
    },
  },
  {
    id: 4,
    part: 3,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_perso: STATICS.SITUATION_PERSO_DIVORCEE,
      revenus: STATICS.REVENUS_577,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '456XX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '02:0.5-14.5',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
      COMPANTRIM: 'BAISSE',
      RUC_RED_quant: '577 < x <942',
      TXEFF_P: '35ETPLUS',
    },
  },
]

// hauts revenus
// représenter plage min-max
const part4 = [
  {
    id: 0,
    part: 4,
    params: {
      genre: STATICS.FEMME,
      age: STATICS.AGE,
      situation_pro: STATICS.SITUATION_PRO_SALARIEE,
      situation_pro: STATICS.SITUATION_PERSO_MARIEE,
      revenus: STATICS.REVENUS_1484,
    },
    scoreData: {
      AGERESP_quant: 'MISSAUT',
      SEQFAM: '23XXX',
      TOPEN19: '0',
      TOPENF1218_P: '1',
      ABANEU: 'AUCUN',
      SEQACR: 'ACT_X__X_',
      NADRESS18_quant: '0 < x <1',
      OPT_NMODLOY18: '01:LOW -0.5, MISSIN',
      TITUBANC: '2',
      OPT_MACT12: '03:14.5-HIGH',
      MOINSCDO_quant: '49 ET PLUS',
      OPT_MOIPIE_MAIL: '03:4.5-HIGH',
    },
  },
]

const config = [...part1, ...part2, ...part3, ...part4]

export { part1, part2, part3, part4, config }
