export const llikelihood2014 = [
  {
    Choice: 'var 1 = -1',
    Variable: 'ABANEU',
    Value: 'AUCUN',
    'Explained Variable FR': 'Abattement ou neutralisation',
    'Explained Variable EN':
      'Allowance or neutralization - NOT SURE WHAT IT MEANS',
    'Explained Value FR': 'Aucun',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Aucun',
    Loglikelihood: '-0.23232764382303',
    Loglikelihood_FR: '-0,23233',
  },
  {
    Choice: 'var 1 = 1',
    Variable: 'ABANEU',
    Value: 'AB. OU NEUTRAL.',
    'Explained Variable FR': 'Abattement ou neutralisation',
    'Explained Variable EN':
      'Allowance or neutralization - NOT SURE WHAT IT MEANS',
    'Explained Value FR': 'Abattement ou Neutralisation',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Ab. Ou Neutral.',
    Loglikelihood: '0.23232764382303',
    Loglikelihood_FR: '0,23233',
  },
  {
    Choice: 'var 25 = (0, 1, 0)',
    Variable: 'SEQACR',
    Value: 'ACT_X__X_',
    'Explained Variable FR': 'Activit\u00e9s des 18 derniers mois',
    'Explained Variable EN': 'Activities in the last 18 months',
    'Explained Value FR':
      'Activit\u00e9 normale, en milieu prot\u00e9g\u00e9, retrait\u00e9 ou \u00e9tudiant sans \u00e9volution',
    defaut: 'oui',
    index: '0',
    'Explained Value EN':
      'Normal activity, in a protected environment (person with a disability), retired or a student with no development',
    Loglikelihood: '0.01494576600753',
    Loglikelihood_FR: '0,01495',
  },
  {
    Choice: 'var 25 = (0, 0, 1)',
    Variable: 'SEQACR',
    Value: '_+__-____',
    'Explained Variable FR': 'Activit\u00e9s des 18 derniers mois',
    'Explained Variable EN': 'Activities in the last 18 months',
    'Explained Value FR':
      "Reprise d'activit\u00e9 / \u00e9tudes apr\u00e8s p\u00e9riode de ch\u00f4mage ou inactivit\u00e9",
    defaut: 'non',
    index: '1',
    'Explained Value EN':
      'Resuming work/entrepreneurship/studies after a period of unemployment or inactivity',
    Loglikelihood: '-0.35411923214215',
    Loglikelihood_FR: '-0,35412',
  },
  {
    Choice: 'var 25 = (-1, -1, -1)',
    Variable: 'SEQACR',
    Value: '_-__-____',
    'Explained Variable FR': 'Activit\u00e9s des 18 derniers mois',
    'Explained Variable EN': 'Activities in the last 18 months',
    'Explained Value FR': 'Ch\u00f4mage puis inactivit\u00e9 ou inversement',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Unemployment followed by inactivity or vice versa',
    Loglikelihood: '0.22907450851623',
    Loglikelihood_FR: '0,22907',
  },
  {
    Choice: 'var 25 = (1, 0, 0)',
    Variable: 'SEQACR',
    Value: '????????',
    'Explained Variable FR': 'Activit\u00e9s des 18 derniers mois',
    'Explained Variable EN': 'Activities in the last 18 months',
    'Explained Value FR': 'Autres',
    defaut: 'non',
    index: '3',
    'Explained Value EN': 'Other',
    Loglikelihood: '0.11009895761839',
    Loglikelihood_FR: '0,11010',
  },
  {
    Choice: 'var 33 = 1',
    Variable: 'AGECON_quant',
    Value: '60 ET PLUS',
    'Explained Variable FR': '\u00c2ge du conjoint',
    'Explained Variable EN': "Partner's age",
    'Explained Value FR': '60 ans et plus',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '60 Et Plus',
    Loglikelihood: '0.27722626019663',
    Loglikelihood_FR: '0,27723',
  },
  {
    Choice: 'var 33 = -1',
    Variable: 'AGECON_quant',
    Value: 'MISSAUT',
    'Explained Variable FR': '\u00c2ge du conjoint',
    'Explained Variable EN': "Partner's age",
    'Explained Value FR': 'Manquant ou autre',
    defaut: 'oui',
    index: '1',
    'Explained Value EN': 'Missing or other',
    Loglikelihood: '-0.27722626019663',
    Loglikelihood_FR: '-0,27723',
  },
  {
    Choice: 'var 34 = 1',
    Variable: 'AGERESP_quant',
    Value: '00 < x < 33',
    'Explained Variable FR': '\u00c2ge du responsable du dossier',
    'Explained Variable EN': "Dossier holder's age",
    'Explained Value FR': 'Moins de 33 ans',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '00 < x < 33',
    Loglikelihood: '0.11334632521637',
    Loglikelihood_FR: '0,11335',
  },
  {
    Choice: 'var 34 = -1',
    Variable: 'AGERESP_quant',
    Value: 'MISSAUT',
    'Explained Variable FR': '\u00c2ge du responsable du dossier',
    'Explained Variable EN': "Dossier holder's age",
    'Explained Value FR': 'Manquant ou autre',
    defaut: 'oui',
    index: '1',
    'Explained Value EN': 'Missing or other',
    Loglikelihood: '-0.11334632521637',
    Loglikelihood_FR: '-0,11335',
  },
  {
    Choice: 'var 9 = (1, 0)',
    Variable: 'NADRESS18_quant',
    Value: '0 < x <1',
    'Explained Variable FR': "Changements d'adresse sur les 18 derniers mois",
    'Explained Variable EN': 'Address changes in the last 18 months',
    'Explained Value FR': "Pas de changement d'adresse",
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0 < x <1',
    Loglikelihood: '0.32426185988357',
    Loglikelihood_FR: '0,32426',
  },
  {
    Choice: 'var 9 = (0, 1)',
    Variable: 'NADRESS18_quant',
    Value: '1 < x <4',
    'Explained Variable FR': "Changements d'adresse sur les 18 derniers mois",
    'Explained Variable EN': 'Address changes in the last 18 months',
    'Explained Value FR': "Entre 1 et 3 changements d'adresse",
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1 < x <4',
    Loglikelihood: '-0.45225170547949',
    Loglikelihood_FR: '-0,45225',
  },
  {
    Choice: 'var 9 = (-1, -1)',
    Variable: 'NADRESS18_quant',
    Value: '4 et +',
    'Explained Variable FR': "Changements d'adresse sur les 18 derniers mois",
    'Explained Variable EN': 'Address changes in the last 18 months',
    'Explained Value FR': "4 changements d'adresse et plus",
    defaut: 'non',
    index: '2',
    'Explained Value EN': '4 et +',
    Loglikelihood: '0.12798984559592003',
    Loglikelihood_FR: '0,12799',
  },
  {
    Choice: 'var 2 = (0, 0, 0, 1)',
    Variable: 'COMPANTRIM',
    Value: 'STABLE',
    'Explained Variable FR': 'Comparaison des revenus annuels/trimestriels',
    'Explained Variable EN': 'Comparison of annual/trimestrial incomes',
    'Explained Value FR': 'Stable',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Stable',
    Loglikelihood: '0.28214016541774',
    Loglikelihood_FR: '0,28214',
  },
  {
    Choice: 'var 2 = (-1, -1, -1, -1)',
    Variable: 'COMPANTRIM',
    Value: 'STABLE0',
    'Explained Variable FR': 'Comparaison des revenus annuels/trimestriels',
    'Explained Variable EN': 'Comparison of annual/trimestrial incomes',
    'Explained Value FR': 'Stable mais nul',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Stable0',
    Loglikelihood: '-0.36608464685773',
    Loglikelihood_FR: '-0,36608',
  },
  {
    Choice: 'var 2 = (0, 1, 0, 0)',
    Variable: 'COMPANTRIM',
    Value: 'BAISSE',
    'Explained Variable FR': 'Comparaison des revenus annuels/trimestriels',
    'Explained Variable EN': 'Comparison of annual/trimestrial incomes',
    'Explained Value FR': 'Baisse',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Baisse',
    Loglikelihood: '-0.23758864170547',
    Loglikelihood_FR: '-0,23759',
  },
  {
    Choice: 'var 2 = (0, 0, 1, 0)',
    Variable: 'COMPANTRIM',
    Value: 'HAUSSE',
    'Explained Variable FR': 'Comparaison des revenus annuels/trimestriels',
    'Explained Variable EN': 'Comparison of annual/trimestrial incomes',
    'Explained Value FR': 'Hausse',
    defaut: 'non',
    index: '3',
    'Explained Value EN': 'Hausse',
    Loglikelihood: '0.10014517695226',
    Loglikelihood_FR: '0,10015',
  },
  {
    Choice: 'var 2 = (1, 0, 0, 0)',
    Variable: 'COMPANTRIM',
    Value: 'AUTRE',
    'Explained Variable FR': 'Comparaison des revenus annuels/trimestriels',
    'Explained Variable EN': 'Comparison of annual/trimestrial incomes',
    'Explained Value FR': 'Autre',
    defaut: 'non',
    index: '4',
    'Explained Value EN': 'Autre',
    Loglikelihood: '0.2213879461932',
    Loglikelihood_FR: '0,22139',
  },
  {
    Choice: 'var 29 = (0, 1)',
    Variable: 'TITUBANC',
    Value: '2',
    'Explained Variable FR':
      'Comparaison du RIB pour les versements et les pr\u00e9l\u00e8vements',
    'Explained Variable EN':
      'Comparison of RIB (Bank Identification Number) for deposit/withdrawal',
    'Explained Value FR': 'Femme ???',
    defaut: 'non',
    index: '0',
    'Explained Value EN': 'Women???',
    Loglikelihood: '-0.30962992811117',
    Loglikelihood_FR: '-0,30963',
  },
  {
    Choice: 'var 29 = (1, 0)',
    Variable: 'TITUBANC',
    Value: '1',
    'Explained Variable FR':
      'Comparaison du RIB pour les versements et les pr\u00e9l\u00e8vements',
    'Explained Variable EN':
      'Comparison of RIB (Bank Identification Number) for deposit/withdrawal',
    'Explained Value FR': 'Homme ???',
    defaut: 'oui',
    index: '1',
    'Explained Value EN': 'Men???',
    Loglikelihood: '-0.2042472331848',
    Loglikelihood_FR: '-0,20425',
  },
  {
    Choice: 'var 29 = (-1, -1)',
    Variable: 'TITUBANC',
    Value: '4',
    'Explained Variable FR':
      'Comparaison du RIB pour les versements et les pr\u00e9l\u00e8vements',
    'Explained Variable EN':
      'Comparison of RIB (Bank Identification Number) for deposit/withdrawal',
    'Explained Value FR': 'Diff\u00e9rence de RIB ???',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Different bank info ???',
    Loglikelihood: '0.51387716129597',
    Loglikelihood_FR: '0,51388',
  },
  {
    Choice: 'var 11 = (1, 0, 0)',
    Variable: 'NBWEB18_quant',
    Value: '0 < x <4',
    'Explained Variable FR':
      'Connexions Web et bornes au cours des 18 derniers mois',
    'Explained Variable EN': 'Web connections within the last 18 months',
    'Explained Value FR': 'Moins de 4 connexions',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '0 < x <4',
    Loglikelihood: '0.02477883999277',
    Loglikelihood_FR: '0,02478',
  },
  {
    Choice: 'var 11 = (-1, -1, -1)',
    Variable: 'NBWEB18_quant',
    Value: '4 < x <12',
    'Explained Variable FR':
      'Connexions Web et bornes au cours des 18 derniers mois',
    'Explained Variable EN': 'Web connections within the last 18 months',
    'Explained Value FR': 'Entre 4 et 11 connexions',
    defaut: 'oui',
    index: '1',
    'Explained Value EN': '4 < x <12',
    Loglikelihood: '0.14185780028173',
    Loglikelihood_FR: '0,14186',
  },
  {
    Choice: 'var 11 = (0, 1, 0)',
    Variable: 'NBWEB18_quant',
    Value: '12 < x <34',
    'Explained Variable FR':
      'Connexions Web et bornes au cours des 18 derniers mois',
    'Explained Variable EN': 'Web connections within the last 18 months',
    'Explained Value FR': 'Entre 12 et 33 connexions',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '12 < x <34',
    Loglikelihood: '-0.11336860212259',
    Loglikelihood_FR: '-0,11337',
  },
  {
    Choice: 'var 11 = (0, 0, 1)',
    Variable: 'NBWEB18_quant',
    Value: '34 < x <=504',
    'Explained Variable FR':
      'Connexions Web et bornes au cours des 18 derniers mois',
    'Explained Variable EN': 'Web connections within the last 18 months',
    'Explained Value FR': 'Plus de 34 connexions',
    defaut: 'non',
    index: '3',
    'Explained Value EN': '34 < x <=504',
    Loglikelihood: '-0.05326803815191',
    Loglikelihood_FR: '-0,05327',
  },
  {
    Choice: 'var 3 = (1, 0, 0)',
    Variable: 'FGRESTRI18_quant',
    Value: '0 < x <1',
    'Explained Variable FR':
      '\u00e9v\u00e8nements "revenus trimestriels" des 18 derniers mois',
    'Explained Variable EN': 'Quarterly income events in the last 18 months',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0 < x <1',
    Loglikelihood: '-0.25528218660984',
    Loglikelihood_FR: '-0,25528',
  },
  {
    Choice: 'var 3 = (0, 1, 0)',
    Variable: 'FGRESTRI18_quant',
    Value: '1 < x <7',
    'Explained Variable FR':
      '\u00e9v\u00e8nements "revenus trimestriels" des 18 derniers mois',
    'Explained Variable EN': 'Quarterly income events in the last 18 months',
    'Explained Value FR': 'Entre 1 et 6',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1 < x <7',
    Loglikelihood: '-0.03407843771333',
    Loglikelihood_FR: '-0,03408',
  },
  {
    Choice: 'var 3 = (-1, -1, -1)',
    Variable: 'FGRESTRI18_quant',
    Value: '7 < x <11',
    'Explained Variable FR':
      '\u00e9v\u00e8nements "revenus trimestriels" des 18 derniers mois',
    'Explained Variable EN': 'Quarterly income events in the last 18 months',
    'Explained Value FR': 'Entre 7 et 10',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '7 < x <11',
    Loglikelihood: '0.041073172373830014',
    Loglikelihood_FR: '0,04107',
  },
  {
    Choice: 'var 3 = (0, 0, 1)',
    Variable: 'FGRESTRI18_quant',
    Value: '11 et +',
    'Explained Variable FR':
      '\u00e9v\u00e8nements "revenus trimestriels" des 18 derniers mois',
    'Explained Variable EN': 'Quarterly income events in the last 18 months',
    'Explained Value FR': '11 et plus',
    defaut: 'non',
    index: '3',
    'Explained Value EN': '11 et +',
    Loglikelihood: '0.24828745194934',
    Loglikelihood_FR: '0,24829',
  },
  {
    Choice: 'var 27 = (0, 0, 0, 0, 1)',
    Variable: 'SEQFAM',
    Value: 'RISQ1',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR': '2 changements de situations',
    defaut: 'non',
    index: '0',
    'Explained Value EN': 'Risq1',
    Loglikelihood: '0.125581957456',
    Loglikelihood_FR: '0,12558',
  },
  {
    Choice: 'var 27 = (0, 0, 0, 1, 0)',
    Variable: 'SEQFAM',
    Value: '7_XXX',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR': 'Pacs sans \u00e9volution',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '7_Xxx',
    Loglikelihood: '-0.49280197200267',
    Loglikelihood_FR: '-0,49280',
  },
  {
    Choice: 'var 27 = (0, 1, 0, 0, 0)',
    Variable: 'SEQFAM',
    Value: '456XX',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR':
      'Veuf-divorc\u00e9-s\u00e9par\u00e9 avec 1 \u00e9volution',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '456Xx',
    Loglikelihood: '0.66925439399747',
    Loglikelihood_FR: '0,66925',
  },
  {
    Choice: 'var 27 = (0, 0, 1, 0, 0)',
    Variable: 'SEQFAM',
    Value: '4_XXX',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR': 'Veuf sans \u00e9volution',
    defaut: 'non',
    index: '3',
    'Explained Value EN': '4_Xxx',
    Loglikelihood: '-0.63687561103914',
    Loglikelihood_FR: '-0,63688',
  },
  {
    Choice: 'var 27 = (1, 0, 0, 0, 0)',
    Variable: 'SEQFAM',
    Value: '23XXX',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR': 'Mari\u00e9-vie maritale sans \u00e9volution',
    defaut: 'non',
    index: '4',
    'Explained Value EN': '23Xxx',
    Loglikelihood: '0.02688244090902',
    Loglikelihood_FR: '0,02688',
  },
  {
    Choice: 'var 27 = (-1, -1, -1, -1, -1)',
    Variable: 'SEQFAM',
    Value: '__X__',
    'Explained Variable FR': '\u00c9volution de la situation familiale',
    'Explained Variable EN': 'Family situation evolution',
    'Explained Value FR': 'Autres situations',
    defaut: 'oui',
    index: '5',
    'Explained Value EN': '__X__',
    Loglikelihood: '0.30795879067931997',
    Loglikelihood_FR: '0,30796',
  },
  {
    Choice: 'var 16 = (1, 0)',
    Variable: 'OPT_MACT12',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      "Mois d'activit\u00e9 sur les 12 derniers mois (Responsable et Conjoint)",
    'Explained Variable EN':
      'Months in activity in the last 12 months (Holder and Partner)',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'non',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '0.27730925279732',
    Loglikelihood_FR: '0,27731',
  },
  {
    Choice: 'var 16 = (0, 1)',
    Variable: 'OPT_MACT12',
    Value: '02:0.5-14.5',
    'Explained Variable FR':
      "Mois d'activit\u00e9 sur les 12 derniers mois (Responsable et Conjoint)",
    'Explained Variable EN':
      'Months in activity in the last 12 months (Holder and Partner)',
    'Explained Value FR': 'Entre 1 et 14 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 0.5 and 14.5',
    Loglikelihood: '0.32522331141171',
    Loglikelihood_FR: '0,32522',
  },
  {
    Choice: 'var 16 = (-1, -1)',
    Variable: 'OPT_MACT12',
    Value: '03:14.5-HIGH',
    'Explained Variable FR':
      "Mois d'activit\u00e9 sur les 12 derniers mois (Responsable et Conjoint)",
    'Explained Variable EN':
      'Months in activity in the last 12 months (Holder and Partner)',
    'Explained Value FR': 'Plus de 15 mois',
    defaut: 'oui',
    index: '2',
    'Explained Value EN': 'Higher 14.5',
    Loglikelihood: '-0.60253256420903',
    Loglikelihood_FR: '-0,60253',
  },
  {
    Choice: 'var 5 = (1, 0)',
    Variable: 'MOINSCDO_quant',
    Value: '0 < x <12',
    'Explained Variable FR': "Mois depuis l'affiliation",
    'Explained Variable EN': 'Months since affiliation',
    'Explained Value FR': 'Entre 0 et 12',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0 < x <12',
    Loglikelihood: '-0.37223848913268',
    Loglikelihood_FR: '-0,37224',
  },
  {
    Choice: 'var 5 = (0, 1)',
    Variable: 'MOINSCDO_quant',
    Value: '12 < x <49',
    'Explained Variable FR': "Mois depuis l'affiliation",
    'Explained Variable EN': 'Months since affiliation',
    'Explained Value FR': 'Entre 12 et 49',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '12 < x <49',
    Loglikelihood: '0.22711099427676',
    Loglikelihood_FR: '0,22711',
  },
  {
    Choice: 'var 5 = (-1, -1)',
    Variable: 'MOINSCDO_quant',
    Value: '49 ET PLUS',
    'Explained Variable FR': "Mois depuis l'affiliation",
    'Explained Variable EN': 'Months since affiliation',
    'Explained Value FR': '49 et plus',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '49 Et Plus',
    Loglikelihood: '0.14512749485592',
    Loglikelihood_FR: '0,14513',
  },
  {
    Choice: 'var 20 = (1, 0)',
    Variable: 'OPT_MOIPIE_MAIL',
    Value: '01:LOW -2.5, MISSIN',
    'Explained Variable FR':
      "Mois depuis l'envoi d'un mail au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since submission of a mail piece in the last 18 months',
    'Explained Value FR': 'Inf\u00e9rieur \u00e0 2 mois ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 2.5 or missing',
    Loglikelihood: '-0.15537483693343',
    Loglikelihood_FR: '-0,15537',
  },
  {
    Choice: 'var 20 = (0, 1)',
    Variable: 'OPT_MOIPIE_MAIL',
    Value: '02:2.5-4.5',
    'Explained Variable FR':
      "Mois depuis l'envoi d'un mail au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since submission of a mail piece in the last 18 months',
    'Explained Value FR': '3 ou 4 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 2.5 and 4.5',
    Loglikelihood: '0.37315035245438',
    Loglikelihood_FR: '0,37315',
  },
  {
    Choice: 'var 20 = (-1, -1)',
    Variable: 'OPT_MOIPIE_MAIL',
    Value: '03:4.5-HIGH',
    'Explained Variable FR':
      "Mois depuis l'envoi d'un mail au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since submission of a mail piece in the last 18 months',
    'Explained Value FR': 'Plus de 5 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Higher 4.5',
    Loglikelihood: '-0.21777551552095',
    Loglikelihood_FR: '-0,21778',
  },
  {
    Choice: 'var 6 = 1',
    Variable: 'MOIPIE_NOTINT_quant',
    Value: '5 < x < 18',
    'Explained Variable FR':
      "Mois depuis l'inscription \u00e0 une information interne",
    'Explained Variable EN':
      'Months since registration of internal information',
    'Explained Value FR': 'Entre 5 et 18',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '5 < x < 18',
    Loglikelihood: '0.4409911195616',
    Loglikelihood_FR: '0,44099',
  },
  {
    Choice: 'var 6 = -1',
    Variable: 'MOIPIE_NOTINT_quant',
    Value: 'MISSAUT',
    'Explained Variable FR':
      "Mois depuis l'inscription \u00e0 une information interne",
    'Explained Variable EN':
      'Months since registration of internal information',
    'Explained Value FR': 'Manquant ou autre',
    defaut: 'oui',
    index: '1',
    'Explained Value EN': 'Missing or other',
    Loglikelihood: '-0.4409911195616',
    Loglikelihood_FR: '-0,44099',
  },
  {
    Choice: 'var 10 = (1, 0, 0)',
    Variable: 'NBM_ODMS_quant',
    Value: '0 < x <1',
    'Explained Variable FR': "Mois depuis l'ouverture des minimums sociaux",
    'Explained Variable EN': 'Months since minimum social benefits opening',
    'Explained Value FR': 'Z\u00e9ro',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0 < x <1',
    Loglikelihood: '-0.39791200043493',
    Loglikelihood_FR: '-0,39791',
  },
  {
    Choice: 'var 10 = (0, 1, 0)',
    Variable: 'NBM_ODMS_quant',
    Value: '1 < x <13',
    'Explained Variable FR': "Mois depuis l'ouverture des minimums sociaux",
    'Explained Variable EN': 'Months since minimum social benefits opening',
    'Explained Value FR': 'Entre 1 et 12 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1 < x <13',
    Loglikelihood: '-0.20817360952199',
    Loglikelihood_FR: '-0,20817',
  },
  {
    Choice: 'var 10 = (0, 0, 1)',
    Variable: 'NBM_ODMS_quant',
    Value: '13 < x <32',
    'Explained Variable FR': "Mois depuis l'ouverture des minimums sociaux",
    'Explained Variable EN': 'Months since minimum social benefits opening',
    'Explained Value FR': 'Entre 13 et 31 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '13 < x <32',
    Loglikelihood: '0.32033067809115',
    Loglikelihood_FR: '0,32033',
  },
  {
    Choice: 'var 10 = (-1, -1, -1)',
    Variable: 'NBM_ODMS_quant',
    Value: '32 < x < 500',
    'Explained Variable FR': "Mois depuis l'ouverture des minimums sociaux",
    'Explained Variable EN': 'Months since minimum social benefits opening',
    'Explained Value FR': 'Plus de 32 mois',
    defaut: 'non',
    index: '3',
    'Explained Value EN': '32 < x < 500',
    Loglikelihood: '0.28575493186577006',
    Loglikelihood_FR: '0,28575',
  },
  {
    Choice: 'var 19 = 1',
    Variable: 'OPT_MOIPIE_DSIT',
    Value: '01:LOW -5.5, MISSIN',
    'Explained Variable FR':
      "Mois depuis le d\u00e9p\u00f4t d'une pi\u00e8ce de d\u00e9claration de situation au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since submission of a situation declaration piece in the last 18 months',
    'Explained Value FR': 'Moins de 5 mois ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 5.5 or missing',
    Loglikelihood: '-0.3597481037668',
    Loglikelihood_FR: '-0,35975',
  },
  {
    Choice: 'var 19 = -1',
    Variable: 'OPT_MOIPIE_DSIT',
    Value: '02:5.5-HIGH',
    'Explained Variable FR':
      "Mois depuis le d\u00e9p\u00f4t d'une pi\u00e8ce de d\u00e9claration de situation au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since submission of a situation declaration piece in the last 18 months',
    'Explained Value FR': 'Plus \u00e0 6 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Higher 5.5',
    Loglikelihood: '0.3597481037668',
    Loglikelihood_FR: '0,35975',
  },
  {
    Choice: 'var 7 = (1, 0)',
    Variable: 'MOIPIE_NPAI_quant',
    Value: '00',
    'Explained Variable FR':
      "Mois depuis le d\u00e9p\u00f4t d'une pi\u00e8ce NPAI (N'habite pas \u00e0 l'adresse indiqu\u00e9)",
    'Explained Variable EN': 'Months since NPAI (undeliverable mail) piece',
    'Explained Value FR': 'Jamais dans les derniers 18 mois',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '00',
    Loglikelihood: '0.10801749528109',
    Loglikelihood_FR: '0,10802',
  },
  {
    Choice: 'var 7 = (-1, -1)',
    Variable: 'MOIPIE_NPAI_quant',
    Value: '1 < x <5',
    'Explained Variable FR':
      "Mois depuis le d\u00e9p\u00f4t d'une pi\u00e8ce NPAI (N'habite pas \u00e0 l'adresse indiqu\u00e9)",
    'Explained Variable EN': 'Months since NPAI (undeliverable mail) piece',
    'Explained Value FR': 'Entre 1 et 5 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1 < x <5',
    Loglikelihood: '-0.41549843678357',
    Loglikelihood_FR: '-0,41550',
  },
  {
    Choice: 'var 7 = (0, 1)',
    Variable: 'MOIPIE_NPAI_quant',
    Value: '05 < x < 18',
    'Explained Variable FR':
      "Mois depuis le d\u00e9p\u00f4t d'une pi\u00e8ce NPAI (N'habite pas \u00e0 l'adresse indiqu\u00e9)",
    'Explained Variable EN': 'Months since NPAI (undeliverable mail) piece',
    'Explained Value FR': 'Entre 5 et 18 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '05 < x < 18',
    Loglikelihood: '0.30748094150248',
    Loglikelihood_FR: '0,30748',
  },
  {
    Choice: 'var 18 = (1, 0)',
    Variable: 'OPT_MOIONTAVU',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      "Mois depuis le dernier contact \u00e0 l'accueil au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since the last contact with reception in the last 18 months',
    'Explained Value FR': 'Jamais dans les derniers 18 mois',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '0.13627815941635',
    Loglikelihood_FR: '0,13628',
  },
  {
    Choice: 'var 18 = (0, 1)',
    Variable: 'OPT_MOIONTAVU',
    Value: '02:0.5-1.5',
    'Explained Variable FR':
      "Mois depuis le dernier contact \u00e0 l'accueil au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since the last contact with reception in the last 18 months',
    'Explained Value FR': '1 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 0.5 and 1.5',
    Loglikelihood: '-0.04374801754763',
    Loglikelihood_FR: '-0,04375',
  },
  {
    Choice: 'var 18 = (-1, -1)',
    Variable: 'OPT_MOIONTAVU',
    Value: '03:1.5-HIGH',
    'Explained Variable FR':
      "Mois depuis le dernier contact \u00e0 l'accueil au cours des 18 derniers mois",
    'Explained Variable EN':
      'Months since the last contact with reception in the last 18 months',
    'Explained Value FR': 'Plus de 2 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Higher 1.5',
    Loglikelihood: '-0.09253014186872',
    Loglikelihood_FR: '-0,09253',
  },
  {
    Choice: 'var 4 = (1, 0, 0, 0)',
    Variable: 'MOICONTVER_quant',
    Value: '1 < x <4',
    'Explained Variable FR': 'Mois depuis le dernier contr\u00f4le',
    'Explained Variable EN': 'Months since the last control',
    'Explained Value FR': 'Entre 1 et 3 mois',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '1 < x <4',
    Loglikelihood: '-0.21768333198141',
    Loglikelihood_FR: '-0,21768',
  },
  {
    Choice: 'var 4 = (0, 0, 1, 0)',
    Variable: 'MOICONTVER_quant',
    Value: '4 < x <7',
    'Explained Variable FR': 'Mois depuis le dernier contr\u00f4le',
    'Explained Variable EN': 'Months since the last control',
    'Explained Value FR': 'Entre 4 et 6 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '4 < x <7',
    Loglikelihood: '0.3753744654792',
    Loglikelihood_FR: '0,37537',
  },
  {
    Choice: 'var 4 = (0, 0, 0, 1)',
    Variable: 'MOICONTVER_quant',
    Value: '7 < x <13',
    'Explained Variable FR': 'Mois depuis le dernier contr\u00f4le',
    'Explained Variable EN': 'Months since the last control',
    'Explained Value FR': 'Entre 7 et 12 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '7 < x <13',
    Loglikelihood: '-0.21053899338984',
    Loglikelihood_FR: '-0,21054',
  },
  {
    Choice: 'var 4 = (0, 1, 0, 0)',
    Variable: 'MOICONTVER_quant',
    Value: '13 < x <=18',
    'Explained Variable FR': 'Mois depuis le dernier contr\u00f4le',
    'Explained Variable EN': 'Months since the last control',
    'Explained Value FR': 'Entre 13 et 18 mois',
    defaut: 'non',
    index: '3',
    'Explained Value EN': '13 < x <=18',
    Loglikelihood: '0.09656226810839',
    Loglikelihood_FR: '0,09656',
  },
  {
    Choice: 'var 4 = (-1, -1, -1, -1)',
    Variable: 'MOICONTVER_quant',
    Value: 'MISSAUT',
    'Explained Variable FR': 'Mois depuis le dernier contr\u00f4le',
    'Explained Variable EN': 'Months since the last control',
    'Explained Value FR': 'Manquant ou autre',
    defaut: 'oui',
    index: '4',
    'Explained Value EN': 'Missing or other',
    Loglikelihood: '-0.04371440821634004',
    Loglikelihood_FR: '-0,04371',
  },
  {
    Choice: 'var 17 = (1, 0)',
    Variable: 'OPT_MOIFGRESAN',
    Value: '01:LOW -0.5',
    'Explained Variable FR':
      'Mois depuis le dernier \u00e9v\u00e8nement ressources annuelles au cours des 18 derniers mois',
    'Explained Variable EN':
      'Months since the last annual income resources event in the last 18 months',
    'Explained Value FR': 'Manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5',
    Loglikelihood: '-0.81202850635466',
    Loglikelihood_FR: '-0,81203',
  },
  {
    Choice: 'var 17 = (0, 1)',
    Variable: 'OPT_MOIFGRESAN',
    Value: '02:0.5-4.5',
    'Explained Variable FR':
      'Mois depuis le dernier \u00e9v\u00e8nement ressources annuelles au cours des 18 derniers mois',
    'Explained Variable EN':
      'Months since the last annual income resources event in the last 18 months',
    'Explained Value FR': 'Entre 1 et 4 mois',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 0.5 and 4.5',
    Loglikelihood: '0.61923386123076',
    Loglikelihood_FR: '0,61923',
  },
  {
    Choice: 'var 17 = (-1, -1)',
    Variable: 'OPT_MOIFGRESAN',
    Value: '03:4.5-HIGH',
    'Explained Variable FR':
      'Mois depuis le dernier \u00e9v\u00e8nement ressources annuelles au cours des 18 derniers mois',
    'Explained Variable EN':
      'Months since the last annual income resources event in the last 18 months',
    'Explained Value FR': 'Plus de 4 mois',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Higher 4.5',
    Loglikelihood: '0.1927946451239',
    Loglikelihood_FR: '0,19279',
  },
  {
    Choice: 'var 8 = (1, 0)',
    Variable: 'MTPAJCAV_quant',
    Value: '0',
    'Explained Variable FR':
      "Montant de la PAJE 'compl\u00e9ment activit\u00e9 versable'",
    'Explained Variable EN': 'Amount of additional childcare allowance',
    'Explained Value FR': '0',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0',
    Loglikelihood: '0.19975598506804',
    Loglikelihood_FR: '0,19976',
  },
  {
    Choice: 'var 8 = (0, 1)',
    Variable: 'MTPAJCAV_quant',
    Value: '0 < x < 361',
    'Explained Variable FR':
      "Montant de la PAJE 'compl\u00e9ment activit\u00e9 versable'",
    'Explained Variable EN': 'Amount of additional childcare allowance',
    'Explained Value FR': 'Entre 0 et 361 euros',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '0 < x < 361',
    Loglikelihood: '0.02474201858734',
    Loglikelihood_FR: '0,02474',
  },
  {
    Choice: 'var 8 = (-1, -1)',
    Variable: 'MTPAJCAV_quant',
    Value: '361 ET+',
    'Explained Variable FR':
      "Montant de la PAJE 'compl\u00e9ment activit\u00e9 versable'",
    'Explained Variable EN': 'Amount of additional childcare allowance',
    'Explained Value FR': '361 euros et plus',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '361 Et+',
    Loglikelihood: '-0.22449800365537997',
    Loglikelihood_FR: '-0,22450',
  },
  {
    Choice: 'var 14 = (1, 0, 0)',
    Variable: 'OPT_FGORINET12',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements d'origine Internet au cours des 12 derniers mois",
    'Explained Variable EN':
      'Number of internet income events in the last 12 months',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '-0.16773363709676',
    Loglikelihood_FR: '-0,16773',
  },
  {
    Choice: 'var 14 = (0, 1, 0)',
    Variable: 'OPT_FGORINET12',
    Value: '02:0.5-2.5',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements d'origine Internet au cours des 12 derniers mois",
    'Explained Variable EN':
      'Number of internet income events in the last 12 months',
    'Explained Value FR': 'Entre 1 et 2',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 0.5 and 2.5',
    Loglikelihood: '0.01415184255654',
    Loglikelihood_FR: '0,01415',
  },
  {
    Choice: 'var 14 = (0, 0, 1)',
    Variable: 'OPT_FGORINET12',
    Value: '03:2.5-5.5',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements d'origine Internet au cours des 12 derniers mois",
    'Explained Variable EN':
      'Number of internet income events in the last 12 months',
    'Explained Value FR': 'Entre 3 et 5',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Between 2.5 and 5.5',
    Loglikelihood: '-0.13428969940581',
    Loglikelihood_FR: '-0,13429',
  },
  {
    Choice: 'var 14 = (-1, -1, -1)',
    Variable: 'OPT_FGORINET12',
    Value: '04:5.5-HIGH',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements d'origine Internet au cours des 12 derniers mois",
    'Explained Variable EN':
      'Number of internet income events in the last 12 months',
    'Explained Value FR': 'Sup\u00e9rieur ou \u00e9gal \u00e0 6',
    defaut: 'non',
    index: '3',
    'Explained Value EN': 'Higher 5.5',
    Loglikelihood: '0.28787149394603',
    Loglikelihood_FR: '0,28787',
  },
  {
    Choice: 'var 15 = 1',
    Variable: 'OPT_FGORIREC18',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements du programme de r\u00e9cup\u00e9ration CDASP au cours des 18 derniers mois",
    'Explained Variable EN':
      'Number of CDASP program recovery income events in the last 18 months',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '-0.15511757943741',
    Loglikelihood_FR: '-0,15512',
  },
  {
    Choice: 'var 15 = -1',
    Variable: 'OPT_FGORIREC18',
    Value: '02:0.5-HIGH',
    'Explained Variable FR':
      "Nombre d'\u00e9v\u00e8nements du programme de r\u00e9cup\u00e9ration CDASP au cours des 18 derniers mois",
    'Explained Variable EN':
      'Number of CDASP program recovery income events in the last 18 months',
    'Explained Value FR': 'Sup\u00e9rieur ou \u00e9gal \u00e0 1',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Higher 0.5',
    Loglikelihood: '0.15511757943741',
    Loglikelihood_FR: '0,15512',
  },
  {
    Choice: 'var 22 = 1',
    Variable: 'OPT_NBPIE_MAIL18',
    Value: '01:LOW -1.5, MISSIN',
    'Explained Variable FR': 'Nombre de mail au cours des 18 derniers mois',
    'Explained Variable EN': 'Number of mail pieces in the last 18 months',
    'Explained Value FR':
      'Inf\u00e9rieur ou \u00e9gal \u00e0 1 mail ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 1.5 or missing',
    Loglikelihood: '0.13623828752591',
    Loglikelihood_FR: '0,13624',
  },
  {
    Choice: 'var 22 = -1',
    Variable: 'OPT_NBPIE_MAIL18',
    Value: '02:1.5-HIGH',
    'Explained Variable FR': 'Nombre de mail au cours des 18 derniers mois',
    'Explained Variable EN': 'Number of mail pieces in the last 18 months',
    'Explained Value FR': 'Sup\u00e9rieur ou \u00e9gal \u00e0 2',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Higher 1.5',
    Loglikelihood: '-0.13623828752591',
    Loglikelihood_FR: '-0,13624',
  },
  {
    Choice: 'var 23 = (1, 0)',
    Variable: 'OPT_NMODLOY18',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      'Nombre de modifications du loyer au cours des 18 derniers mois',
    'Explained Variable EN':
      'Number of rent modifications in the last 18 months',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '-0.54676525776417',
    Loglikelihood_FR: '-0,54677',
  },
  {
    Choice: 'var 23 = (0, 1)',
    Variable: 'OPT_NMODLOY18',
    Value: '02:0.5-4.5',
    'Explained Variable FR':
      'Nombre de modifications du loyer au cours des 18 derniers mois',
    'Explained Variable EN':
      'Number of rent modifications in the last 18 months',
    'Explained Value FR': 'Entre 1 et 4',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Between 0.5 and 4.5',
    Loglikelihood: '-0.31601088054791',
    Loglikelihood_FR: '-0,31601',
  },
  {
    Choice: 'var 23 = (-1, -1)',
    Variable: 'OPT_NMODLOY18',
    Value: '03:4.5-HIGH',
    'Explained Variable FR':
      'Nombre de modifications du loyer au cours des 18 derniers mois',
    'Explained Variable EN':
      'Number of rent modifications in the last 18 months',
    'Explained Value FR': 'Sup\u00e9rieur \u00e0 5',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Higher 4.5',
    Loglikelihood: '0.86277613831208',
    Loglikelihood_FR: '0,86278',
  },
  {
    Choice: 'var 21 = 1',
    Variable: 'OPT_NBPIE_DSIT18',
    Value: '01:LOW -0.5, MISSIN',
    'Explained Variable FR':
      'Nombre de pi\u00e8ces de d\u00e9claration de situation au cours des 18 derniers mois',
    'Explained Variable EN':
      'Number of situation declaration pieces in the last 18 months',
    'Explained Value FR': 'Z\u00e9ro ou manquant',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'Lower than 0.5 or missing',
    Loglikelihood: '0.29525355588199',
    Loglikelihood_FR: '0,29525',
  },
  {
    Choice: 'var 21 = -1',
    Variable: 'OPT_NBPIE_DSIT18',
    Value: '02:0.5-HIGH',
    'Explained Variable FR':
      'Nombre de pi\u00e8ces de d\u00e9claration de situation au cours des 18 derniers mois',
    'Explained Variable EN':
      'Number of situation declaration pieces in the last 18 months',
    'Explained Value FR': 'Sup\u00e9rieur ou \u00e9gal \u00e0 1',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Higher 0.5',
    Loglikelihood: '-0.29525355588199',
    Loglikelihood_FR: '-0,29525',
  },
  {
    Choice: 'var 32 = (1, 0)',
    Variable: 'TYPAAH',
    Value: '0',
    'Explained Variable FR':
      "P\u00e9riodicit\u00e9 de d\u00e9claration de l'AAH",
    'Explained Variable EN':
      'Annual or quarterly AAH (Allocation aux Adultes Handicap\u00e9s) periodicity',
    'Explained Value FR': "Pas d'AAH",
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'No disability pension',
    Loglikelihood: '-0.21025373930299',
    Loglikelihood_FR: '-0,21025',
  },
  {
    Choice: 'var 32 = (0, 1)',
    Variable: 'TYPAAH',
    Value: '1',
    'Explained Variable FR':
      "P\u00e9riodicit\u00e9 de d\u00e9claration de l'AAH",
    'Explained Variable EN':
      'Annual or quarterly AAH (Allocation aux Adultes Handicap\u00e9s) periodicity',
    'Explained Value FR': 'Trimestriel',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Quarterly?',
    Loglikelihood: '0.72818206088848',
    Loglikelihood_FR: '0,72818',
  },
  {
    Choice: 'var 32 = (-1, -1)',
    Variable: 'TYPAAH',
    Value: '2',
    'Explained Variable FR':
      "P\u00e9riodicit\u00e9 de d\u00e9claration de l'AAH",
    'Explained Variable EN':
      'Annual or quarterly AAH (Allocation aux Adultes Handicap\u00e9s) periodicity',
    'Explained Value FR': 'Annuel',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Yearly?',
    Loglikelihood: '-0.5179283215854901',
    Loglikelihood_FR: '-0,51793',
  },
  {
    Choice: 'var TOPEN19 = 0',
    Variable: 'TOPEN19',
    Value: '0',
    'Explained Variable FR': "Pr\u00e9sence d'enfants de 19 ans et plus",
    'Explained Variable EN': 'Presence of children aged 19 and over',
    'Explained Value FR': 'Non',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0',
    Loglikelihood: '0.0',
    Loglikelihood_FR: '0,00000',
  },
  {
    Choice: 'var TOPEN19 = 1',
    Variable: 'TOPEN19',
    Value: '1',
    'Explained Variable FR': "Pr\u00e9sence d'enfants de 19 ans et plus",
    'Explained Variable EN': 'Presence of children aged 19 and over',
    'Explained Value FR': 'Oui',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1',
    Loglikelihood: '0.89385926213357',
    Loglikelihood_FR: '0,89386',
  },
  {
    Choice: 'var 30 = 1',
    Variable: 'TOPENF1218_P',
    Value: '0',
    'Explained Variable FR': "Pr\u00e9sence d'enfants entre 12 et 18 ans",
    'Explained Variable EN': 'Presence of children aged between 12 and 18',
    'Explained Value FR': 'Non',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0',
    Loglikelihood: '-0.08779929863942',
    Loglikelihood_FR: '-0,08780',
  },
  {
    Choice: 'var 30 = -1',
    Variable: 'TOPENF1218_P',
    Value: '1',
    'Explained Variable FR': "Pr\u00e9sence d'enfants entre 12 et 18 ans",
    'Explained Variable EN': 'Presence of children aged between 12 and 18',
    'Explained Value FR': 'Oui',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '1',
    Loglikelihood: '0.08779929863942',
    Loglikelihood_FR: '0,08780',
  },
  {
    Choice: 'var 35 = 1',
    Variable: 'TUT_P',
    Value: '0',
    'Explained Variable FR': "Pr\u00e9sence d'une tutelle",
    'Explained Variable EN': 'Presence of guardianship',
    'Explained Value FR': 'Non',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0',
    Loglikelihood: '0.60450601197118',
    Loglikelihood_FR: '0,60451',
  },
  {
    Choice: 'var 35 = -1',
    Variable: 'TUT_P',
    Value: 'TUTELLE',
    'Explained Variable FR': "Pr\u00e9sence d'une tutelle",
    'Explained Variable EN': 'Presence of guardianship',
    'Explained Value FR': 'Tutelle',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Tutelle',
    Loglikelihood: '-0.60450601197118',
    Loglikelihood_FR: '-0,60451',
  },
  {
    Choice: 'var 24 = (1, 0, 0)',
    Variable: 'RUC_RED_quant',
    Value: '0 < x <577',
    'Explained Variable FR':
      'Revenu mensuel par unit\u00e9 de consommation hors prestations familiales',
    'Explained Variable EN':
      'Monthly income per consumption unit excluding PF (Personal Fund)',
    'Explained Value FR': 'Moins de 577 euros par unit\u00e9 de consommation',
    defaut: 'non',
    index: '0',
    'Explained Value EN': '0 < x <577',
    Loglikelihood: '0.33484019169728',
    Loglikelihood_FR: '0,33484',
  },
  {
    Choice: 'var 24 = (0, 0, 1)',
    Variable: 'RUC_RED_quant',
    Value: '577 < x <942',
    'Explained Variable FR':
      'Revenu mensuel par unit\u00e9 de consommation hors prestations familiales',
    'Explained Variable EN':
      'Monthly income per consumption unit excluding PF (Personal Fund)',
    'Explained Value FR': 'Entre 577 et 941 euros',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '577 < x <942',
    Loglikelihood: '0.43094626466292',
    Loglikelihood_FR: '0,43095',
  },
  {
    Choice: 'var 24 = (-1, -1, -1)',
    Variable: 'RUC_RED_quant',
    Value: '942 < x <1483.33',
    'Explained Variable FR':
      'Revenu mensuel par unit\u00e9 de consommation hors prestations familiales',
    'Explained Variable EN':
      'Monthly income per consumption unit excluding PF (Personal Fund)',
    'Explained Value FR': 'Entre 942 et 1483,33 euros',
    defaut: 'non',
    index: '2',
    'Explained Value EN': '942 < x <1483.33',
    Loglikelihood: '0.025971514081119973',
    Loglikelihood_FR: '0,02597',
  },
  {
    Choice: 'var 24 = (0, 1, 0)',
    Variable: 'RUC_RED_quant',
    Value: '1483.33 < x <=19745',
    'Explained Variable FR':
      'Revenu mensuel par unit\u00e9 de consommation hors prestations familiales',
    'Explained Variable EN':
      'Monthly income per consumption unit excluding PF (Personal Fund)',
    'Explained Value FR': 'Plus de 1483,33 euros',
    defaut: 'oui',
    index: '3',
    'Explained Value EN': '1483.33 < x <=19745',
    Loglikelihood: '-0.79175797044132',
    Loglikelihood_FR: '-0,79176',
  },
  {
    Choice: 'var 28 = (1, 0)',
    Variable: 'STATUETU',
    Value: '0',
    'Explained Variable FR': 'Statut \u00e9tudiant ou apprenti',
    'Explained Variable EN': 'Student apprentice status',
    'Explained Value FR': 'Non',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': 'None',
    Loglikelihood: '0.26847813628468',
    Loglikelihood_FR: '0,26848',
  },
  {
    Choice: 'var 28 = (0, 1)',
    Variable: 'STATUETU',
    Value: '1',
    'Explained Variable FR': 'Statut \u00e9tudiant ou apprenti',
    'Explained Variable EN': 'Student apprentice status',
    'Explained Value FR': 'Etudiant',
    defaut: 'non',
    index: '1',
    'Explained Value EN': 'Student??',
    Loglikelihood: '-0.49231217017174',
    Loglikelihood_FR: '-0,49231',
  },
  {
    Choice: 'var 28 = (-1, -1)',
    Variable: 'STATUETU',
    Value: '3',
    'Explained Variable FR': 'Statut \u00e9tudiant ou apprenti',
    'Explained Variable EN': 'Student apprentice status',
    'Explained Value FR': 'Apprenti',
    defaut: 'non',
    index: '2',
    'Explained Value EN': 'Apprentice??',
    Loglikelihood: '0.22383403388706002',
    Loglikelihood_FR: '0,22383',
  },
  {
    Choice: 'var 31 = 1',
    Variable: 'TXEFF_P',
    Value: '0ALETTXEFF 0A35',
    'Explained Variable FR': "Taux d'effort pour le logement",
    'Explained Variable EN': 'Housing affordability rate',
    'Explained Value FR': 'Moins de 35 %',
    defaut: 'oui',
    index: '0',
    'Explained Value EN': '0Alettxeff 0A35',
    Loglikelihood: '-0.09635968487988',
    Loglikelihood_FR: '-0,09636',
  },
  {
    Choice: 'var 31 = -1',
    Variable: 'TXEFF_P',
    Value: '35ETPLUS',
    'Explained Variable FR': "Taux d'effort pour le logement",
    'Explained Variable EN': 'Housing affordability rate',
    'Explained Value FR': '35 % et plus',
    defaut: 'non',
    index: '1',
    'Explained Value EN': '35Etplus',
    Loglikelihood: '0.09635968487988',
    Loglikelihood_FR: '0,09636',
  },
]
