export const texts = {
  intro: {
    title:
      'Age, situation familiale, revenus&nbsp;: comment la CAF note ses allocataires',
    publication: 'Publié le 5 décembre 2023',
    signature:
      'Par Manon&nbsp;Romain, Adrien&nbsp;Sénécat, Elsa&nbsp;Delmas, Léa&nbsp;Girardot et Thomas&nbsp;Steffen',
  },
  simulation: {
    name: 'Nathalie',
    scoreLimit: 'Risque&nbsp;de&nbsp;contrôle',
    conjoint1: 'Conjoint de',
    conjoint2: 'ans',
    valide: 'Valide',
    valides: 'Valides',
    plus34ans: 'Plus de 34 ans',
    entre35et60ans: 'Entre 35 et 60 ans',
    situationPersoMariee: 'Mariée',
    situationPersoMarie: 'Marié',
    situationPersoDivorcee: 'Divorcée',
    conjointMoins60ans: 'Conjoint de moins de 60 ans',
    activiteSalariee: 'En activité salariée',
    moisActivite12: "12 mois d'activité sur la dernière année",
    moisActivite24: "24 mois d'activité sur la dernière année",
    revenus1484: 'Revenu ajusté de plus de 1484&nbsp;euros par personne',
    revenus942: 'Revenu ajusté de plus de 942&nbsp;euros par personne',
    revenus577: 'Revenu ajusté de plus de 577&nbsp;euros par personne',
    revenusStables: 'Revenus stables et importants',
    pasMinimaSociaux: 'Pas de minima sociaux',
    enfantMoins18ans: 'Enfant de 12 à 18 ans',
    enfantMoins12ans: 'Enfants de moins de 12 ans',
    inscritePlus4ans: 'Inscrite à la CAF depuis plus de 4&nbsp;ans',
    inscritPlus4ans: 'Inscrit à la CAF depuis plus de 4&nbsp;ans',
    pasChangementAdresse: "Pas de changement d'adresse",
    pasChangementLoyer: 'Pas de changement de loyer',
    mail4mois: 'Mail à la CAF il y a plus de 4 mois',
    toucheAAH: "Touche l'AAH",
    jamaisControle: 'Jamais contrôlé auparavant',
  },
}
